### PR TITLE
Pull request: add new operations for `IMP-`

### PR DESCRIPTION
**Pull request by BilelGho**
create new operations as mentioned in issue #29

### CODE REVIEW

**Comment by BilelGho** [comment]
@notiho I hope that'll do it. let me know.
@mabdula @maxhaslbeck checking this theory I thought that we could use some syntactic sugar over here. But I don't know how to actually do it. What do you think? if you approve are there some resources about it ?

**Comment by notiho** [comment]
Yeah looks like what we want

**Comment by mabdula** [comment]
I think adding syntax could make things look nicer. Do you want an example of new syntax constructs in Isabelle?

**Comment by BilelGho** [comment]
@notiho @mabdula @maxhaslbeck  any suggestions to improve the syntax? Please check the last commit. If it is okay then please approve the PR.

**Review by mabdula — APPROVED** [review]
I think the syntax is fine.

**Pull request merged**
